# Generated by Django 2.1.7 on 2019-03-10 06:44

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('app_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='App ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_html', models.TextField(blank=True, null=True, verbose_name='HTML Description')),
                ('developer_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Developer ID')),
                ('developer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Developer')),
                ('developer_address', models.TextField(blank=True, null=True, verbose_name='Developer Address')),
                ('developer_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Developer Email')),
                ('developer_url', models.URLField(blank=True, null=True, verbose_name='Developer URL')),
                ('free', models.BooleanField(default=False, verbose_name='Is Free')),
                ('full_price', models.CharField(blank=True, max_length=50, null=True, verbose_name='Full Price')),
                ('icon', models.URLField(blank=True, null=True, verbose_name='Icon')),
                ('price', models.CharField(blank=True, max_length=50, null=True, verbose_name='Price')),
                ('score', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rating')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='Category')),
                ('content_rating', models.CharField(blank=True, max_length=255, null=True, verbose_name='Content Rating')),
                ('current_version', models.CharField(blank=True, max_length=100, null=True, verbose_name='Current Version')),
                ('editors_choice', models.BooleanField(default=False, verbose_name='Editors Choice')),
                ('installs', models.CharField(blank=True, max_length=50, null=True, verbose_name='Installs')),
                ('recent_changes', models.TextField(blank=True, null=True, verbose_name='Recent Changes')),
                ('required_android_version', models.CharField(blank=True, max_length=100, null=True, verbose_name='Android Version')),
                ('reviews', models.CharField(blank=True, max_length=50, null=True, verbose_name='Reviews')),
                ('screenshots', models.TextField(blank=True, null=True, verbose_name='Screenshots')),
                ('size', models.CharField(blank=True, max_length=50, null=True, verbose_name='Size')),
                ('updated', models.DateField(blank=True, null=True, verbose_name='Updated')),
                ('video', models.TextField(blank=True, null=True, verbose_name='Video')),
            ],
            options={
                'verbose_name': 'App',
                'verbose_name_plural': 'Apps',
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('query', models.TextField(blank=True, null=True, unique=True, verbose_name='Search Query')),
            ],
            options={
                'verbose_name': 'Search Query',
                'verbose_name_plural': 'Search Queries',
            },
        ),
    ]
